{% set version = "2.0.0" %}
{% set name = "cykhash" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ab2e7b3a701291f71df626d8fe597a50b097c1b33e25b4c37681415639d270fd

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=0.28
  run:
    - python

test:
  imports:
    - cykhash

about:
  home: https://github.com/realead/cykhash
  license: MIT
  license_file: LICENSE
  summary: cython wrapper for khash-sets/maps, efficient implementation of `isin` and `unique`

extra:
  recipe-maintainers:
    - htenkanen
    - realead
